import os
import sys
import json
import uuid
import time
from dotenv import load_dotenv

# Ensure local path is configured
sys.path.append(os.path.dirname(os.path.abspath(__file__)))

# Load environmental variables
load_dotenv()

from google.adk.runners import Runner
from google.adk.sessions.in_memory_session_service import InMemorySessionService
from google.genai import types

from agents.sensory_guardian import sensory_guardian_agent
from agents.cognitive_companion import cognitive_companion_agent
from agents.medical_compliance import medical_compliance_agent
from agents.care_coordinator import care_coordinator_agent
from tools.trace_events import TraceCollector

# Initialize one global Session Service for the application
session_service = InMemorySessionService()

# Create standard ADK Runners for all 4 agents
sensory_runner = Runner(agent=sensory_guardian_agent, app_name="silvergrove", session_service=session_service, auto_create_session=True)
compliance_runner = Runner(agent=medical_compliance_agent, app_name="silvergrove", session_service=session_service, auto_create_session=True)
companion_runner = Runner(agent=cognitive_companion_agent, app_name="silvergrove", session_service=session_service, auto_create_session=True)
coordinator_runner = Runner(agent=care_coordinator_agent, app_name="silvergrove", session_service=session_service, auto_create_session=True)

def invoke_agent(runner: Runner, prompt: str, user_id: str, session_id: str, collector: TraceCollector = None) -> str:
    """
    Helper function to run an agent via its stateful ADK Runner.
    Translates string prompts into Google GenAI types.Content, consumes yielded events,
    and extracts the final text response. Includes a 3-attempt retry policy for free tier robustness.
    Strictly emoji-free logging.
    """
    agent_name = runner.agent.name
    if collector:
        collector.log(
            agent=agent_name,
            event_type="LLM_REQUEST",
            message=f"Invoking Gemini 3.1 Flash Lite on model {runner.agent.model or 'gemini-3.1-flash-lite'}",
            data={"prompt": prompt}
        )

    content = types.Content(role="user", parts=[types.Part.from_text(text=prompt)])
    
    for attempt in range(1, 4):
        try:
            if collector and attempt > 1:
                collector.log(
                    agent=agent_name,
                    event_type="RETRY",
                    message=f"Attempt {attempt} to execute agent after failure"
                )
            
            # Run the generator synchronously to collect all events
            events = list(runner.run(user_id=user_id, session_id=session_id, new_message=content))
            
            # Extract response and log tool events
            response_text = ""
            for event in events:
                # Log any tool calls made by the agent
                if hasattr(event, "tool_calls") and event.tool_calls:
                    for tc in event.tool_calls:
                        tool_args = getattr(tc, "args", {}) or {}
                        tool_name = getattr(tc, "name", "unknown_tool")
                        if collector:
                            collector.log(
                                agent=agent_name,
                                event_type="TOOL_CALL",
                                message=f"Calling tool: {tool_name}",
                                data={"args": tool_args}
                            )
                
                # Check for tool response/results
                if hasattr(event, "tool_response") and event.tool_response:
                    if collector:
                        collector.log(
                            agent=agent_name,
                            event_type="TOOL_RESULT",
                            message="Tool execution successful",
                            data={"result": str(event.tool_response)[:500]}
                        )
                        
                if hasattr(event, "content") and event.content:
                    for part in event.content.parts:
                        if part.text:
                            response_text += part.text
                            
            if not response_text:
                for event in events:
                    if hasattr(event, "output") and event.output:
                        if isinstance(event.output, str):
                            response_text += event.output
                        elif hasattr(event.output, "text") and event.output.text:
                            response_text += event.output.text
                            
            if response_text and "empty response" not in response_text.lower():
                if collector:
                    collector.log(
                        agent=agent_name,
                        event_type="LLM_RESPONSE",
                        message="Response successfully generated by agent",
                        data={"response": response_text}
                    )
                return response_text
                
            raise ValueError("Agent returned an empty or invalid response.")
            
        except Exception as e:
            print(f"[Retry Warning] Attempt {attempt} failed: {e}. Retrying in 2 seconds...")
            time.sleep(2)
            
    # All 3 retry attempts exhausted -- propagate transparent error to the frontend
    error_msg = f"Agent '{agent_name}' failed to generate a response after 3 attempts. Verify API key and network connectivity."
    if collector:
        collector.log(
            agent=agent_name,
            event_type="ERROR",
            message=error_msg
        )
    raise RuntimeError(error_msg)


class SilverGroveOrchestrator:
    """
    SilverGrove Multi-Agent Orchestrator.
    Coordinates sequential execution and state handover across all 4 agents
    using stateful ADK Runner sessions. Emits structured logs.
    """
    
    def run_health_check(self, resident_id: str, collector: TraceCollector = None) -> dict:
        print(f"\n[SilverGrove] Starting end-to-end multi-agent clinical check for: {resident_id}")
        
        # Generate unique session IDs for each run to prevent state pollution
        run_session_id = f"session_{uuid.uuid4().hex[:8]}"
        user_id = f"user_{resident_id}"
        
        if collector:
            collector.log(
                agent="ORCHESTRATOR",
                event_type="START",
                message=f"Beginning end-to-end multi-agent clinical audit",
                data={"resident_id": resident_id, "session_id": run_session_id}
            )
        
        trajectory = {
            "resident_id": resident_id,
            "session_id": run_session_id,
            "sensory_guardian": {"status": "SKIPPED", "output": ""},
            "medical_compliance": {"status": "SKIPPED", "output": ""},
            "cognitive_companion": {"status": "SKIPPED", "output": ""},
            "care_coordinator": {"status": "SKIPPED", "output": ""},
            "summary": "No critical anomalies detected. Routine vitals are within stable thresholds."
        }
        
        # --- Step 1: Sensory Guardian Anomaly Detection ---
        if collector:
            collector.log("ORCHESTRATOR", "STAGE", "Activating Step 1: Sensory Guardian Anomaly Detection")
        
        sensory_prompt = (
            f"Analyze vital sign readings, baselines, and 5-day gait history for resident '{resident_id}'. "
            "Report if there are any significant anomalies (elevated/low blood pressure or gait speed slowdown >=15%)."
        )
        try:
            sensory_response = invoke_agent(sensory_runner, sensory_prompt, user_id, run_session_id, collector)
            trajectory["sensory_guardian"] = {
                "status": "COMPLETED",
                "output": sensory_response
            }
        except Exception as e:
            if collector:
                collector.log("ORCHESTRATOR", "ERROR", f"Sensory Guardian execution failed: {str(e)}")
            trajectory["sensory_guardian"] = {"status": "FAILED", "output": str(e)}
            return trajectory

        # Evaluate if an anomaly was flagged
        has_anomaly = any(
            word in sensory_response.upper() 
            for word in ["ANOMALY", "WARNING", "DEGRADATION", "BP ELEVATED", "SLOWDOWN", "ELEVATED", "SPIKE", "ALERT", "LOW BLOOD PRESSURE", " hypotension"]
        )
        
        if not has_anomaly:
            msg = "Vitals are normal. No clinical escalation needed."
            if collector:
                collector.log("ORCHESTRATOR", "COMPLETE", msg)
            trajectory["summary"] = msg
            return trajectory
            
        # --- Step 2: Medical Compliance Clinical Correlation ---
        if collector:
            collector.log("ORCHESTRATOR", "HANDOFF", "Anomaly flagged. Routing to Step 2: Medical Compliance Agent")
        
        compliance_prompt = (
            f"An anomaly was flagged for resident '{resident_id}'. Here is the Sensory Guardian's report:\n"
            f"\"\"\"{sensory_response}\"\"\"\n"
            "Look up their current prescriptions and active conditions. Determine if any new medication started "
            "recently could chemically correlate with the observed symptoms. Provide a structured Clinical Correlation Report."
        )
        try:
            compliance_response = invoke_agent(compliance_runner, compliance_prompt, user_id, run_session_id, collector)
            trajectory["medical_compliance"] = {
                "status": "COMPLETED",
                "output": compliance_response
            }
        except Exception as e:
            if collector:
                collector.log("ORCHESTRATOR", "ERROR", f"Medical Compliance execution failed: {str(e)}")
            trajectory["medical_compliance"] = {"status": "FAILED", "output": str(e)}
            return trajectory

        # Extract risk level from compliance report
        risk_level = "WARNING"
        if "CRITICAL" in compliance_response.upper():
            risk_level = "CRITICAL"
        elif "MODERATE" in compliance_response.upper():
            risk_level = "WARNING"
        elif "LOW" in compliance_response.upper():
            risk_level = "ADVISORY"

        # --- Step 3: Cognitive Companion Empathetic Check-in ---
        if collector:
            collector.log("ORCHESTRATOR", "HANDOFF", "Clinical analysis complete. Handing over to Step 3: Cognitive Companion")
            
        companion_prompt = (
            f"You need to speak to resident '{resident_id}'. The Medical Compliance Agent completed an analysis:\n"
            f"\"\"\"{compliance_response}\"\"\"\n"
            "Write a warm, simple, check-in conversational message to the resident. Ask if they have been feeling "
            "dizzy, tell them we noticed some mild changes, and give them the key safety advice from the report (such as standing slowly and drinking water)."
        )
        try:
            companion_response = invoke_agent(companion_runner, companion_prompt, user_id, run_session_id, collector)
            trajectory["cognitive_companion"] = {
                "status": "COMPLETED",
                "output": companion_response
            }
        except Exception as e:
            if collector:
                collector.log("ORCHESTRATOR", "ERROR", f"Cognitive Companion execution failed: {str(e)}")
            trajectory["cognitive_companion"] = {"status": "FAILED", "output": str(e)}
            return trajectory

        # --- Step 4: Care Coordinator A2A Gateway Alert Routing ---
        if collector:
            collector.log("ORCHESTRATOR", "HANDOFF", "Handoff to Step 4: Care Coordinator for A2A dispatch")
            
        coordinator_prompt = (
            f"We have an active health situation for resident '{resident_id}'.\n"
            f"- Clinical Risk: {risk_level}\n"
            f"- Compliance Summary: {compliance_response[:500]}...\n"
            f"- Companion Check-in Draft: {companion_response[:300]}...\n\n"
            "Please route this care alert. Look up the resident details to get their full name. "
            "Invoke the log_a2a_alert_tool with appropriate parameters. Use a semicolon-separated list of actions "
            "for the companion instructions."
        )
        try:
            coordinator_response = invoke_agent(coordinator_runner, coordinator_prompt, user_id, run_session_id, collector)
            trajectory["care_coordinator"] = {
                "status": "COMPLETED",
                "output": coordinator_response
            }
        except Exception as e:
            if collector:
                collector.log("ORCHESTRATOR", "ERROR", f"Care Coordinator execution failed: {str(e)}")
            trajectory["care_coordinator"] = {"status": "FAILED", "output": str(e)}
            return trajectory
            
        summary_msg = (
            f"End-to-end clinical check complete. Multi-agent consensus: {risk_level} risk. "
            "A2A alerts dispatched to family and primary care physician. Empathetic resident check-in prepared."
        )
        if collector:
            collector.log("ORCHESTRATOR", "COMPLETE", f"Multi-agent consensus completed successfully: {risk_level} risk")
            
        trajectory["summary"] = summary_msg
        return trajectory

if __name__ == "__main__":
    # Test orchestrator locally
    orchestrator = SilverGroveOrchestrator()
    collector = TraceCollector("test_session")
    res = orchestrator.run_health_check("martha_001", collector)
    print("\n--- HEALTH CHECK SUMMARY ---")
    print(res["summary"])
